githubClientSecret: AgBVV/8Lis+AxRHx8oggFg0Ked2DZQutPhy1e45VbIBWVyQrok31YhbwH9LPEDKyQcDUsb/1CHMh3wb5cYtZF5pD3eknbir3n8CJvRwYKPICUlY9yqq1zQ/WcMHz3G01Tsfbib3E/We9XRHtu4SwAx1PT/t/uNNw5mfKaUvn2YgXjWCqXEiu2Qb6fTwuWK6+L81FldgVc449e2yPrVoBJvAYik5/JiQJQ681WPySs2OeRGPCcqvl1+1p/LvX3wtUw5f2orHHBxBmBc+nXNzvwtemKlgE9+p6oPKHNnEeM8ykbJ1UiTQ+Dt1kAfXiq6m3ZzW27/6tr5IEo9hTiJB7gmjI3tW9htcmG6+Y7lIpX9UxtSm7pdmJYN/ARcciXBrZ3Koz/4OcBIptvWkBuW46fzADpGf1NSblYYdkQPd0lbAPmfhZrgCDmIv/BVVeEU5B3iPzYdyDrYkY3uEcBJKiEsl6TQZ+gJC9+jEpibS6ZBlwqKkjZ9voHsHYpfZr8bT2iaXbYDBBE14A6a7VToQDQ3lpwMvxqV4jEv97x4lPv35IJ2DiEcjerDNTER9BlNnYvNelVVyaLmp/U6WerMT8SpdMHlRogeWsns2/2w8XOBGBb/ZEGUHQ8b/LZ/4VYHdPkvNafStYgeU+OgEcfkaq+fOV4WmtYTcUgl1CdK0UevBZ1wSVVRV/liWWxHaBMtQR0hAKS4EC

argo-cd:
  global:
    logging:
      format: json

  configs:
    repositories:
      istio-helm-repo:
        type: helm
        name: istio
        url: https://istio-release.storage.googleapis.com/charts
    cm:
      url: argocd.carstens.tech
      # TODO: create SealedSecret for clientSecret
      # admin.enabled: false
    # dex.config:
    #   connectors:
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientId: ...
    #         clientSecret: $github-secret.github.clientSecret
    #         orgs:
    #         - name: OpenAlcoholics

  dex:
    enabled: false

  server:
    ingress:
      enabled: true
      hosts:
        - argocd.carstens.tech
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        cert-manager.io/issue-temporary-certificate: "false"
        kubernetes.io/tls-acme: "true"

  applicationSet:
    enabled: false

  notifications:
    enabled: false
