argo-cd:
  global:
    logging:
      format: json
      level: warn

  configs:
    params:
      server.insecure: true
    repositories:
      rancher-helm-repo:
        type: helm
        name: rancher
        url: https://charts.rancher.io
    cm:
      url: https://argocd.woog.chat
      # TODO: create SealedSecret for clientSecret
      # admin.enabled: false
    # dex.config:
    #   connectors:
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientId: ...
    #         clientSecret: $github-secret.github.clientSecret
    #         orgs:
    #         - name: BlindfoldedSurgery

  dex:
    enabled: false

  server:
    ingress:
      enabled: true
      hosts:
        - argocd.woog.chat
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        cert-manager.io/issue-temporary-certificate: "false"
        kubernetes.io/tls-acme: "true"
      tls:
        - secretName: argocd-tls
          hosts:
            - argocd.woog.chat
      ingressClassName: nginx
      https: false

  applicationSet:
    enabled: false

  notifications:
    enabled: false
