github:
  namespace: argocd
  clientSecret:
    name: github-secret
    secretStoreName: mgmt-prod
    data:
    - secretKey: clientSecret
      remoteRef:
        key: ARGOCD_GITHUB_CLIENT_SECRET

argo-cd:
  global:
    logging:
      format: json
      level: warn

  configs:
    params:
      server.insecure: true
    repositories:
      rancher-helm-repo:
        type: helm
        name: rancher
        url: https://charts.rancher.io
    cm:
      url: https://argocd.blindfolded.surgery
      admin.enabled: false
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientId: e8f50f1c89197fa53980
              clientSecret: $github-secret:clientSecret
              orgs:
              - name: BlindfoldedSurgery
    rbac:
      policy.csv: |
        g, BlindfoldedSurgery:Owners, role:admin
      policy.default: "role:readonly"

  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      rules:
        enabled: true
        spec:
        - alert: ArgoAppMissing
          expr: |
            absent(argocd_app_info) == 1
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "[Argo CD] No reported applications"
            description: >
              Argo CD has not reported any applications data for the past 15 minutes which
              means that it must be down or not functioning properly.  This needs to be
              resolved for this cloud to continue to maintain state.
        - alert: ArgoAppNotSynced
          expr: |
            argocd_app_info{sync_status!="Synced"} == 1
          for: 12h
          labels:
            severity: warning
          annotations:
            summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
            description: >
              The application [{{`{{$labels.name}}`}} has not been synchronized for over
              12 hours which means that the state of this cloud has drifted away from the
              state inside Git.
        - alert: ArgoAppNotHealthy
          # see https://github.com/argoproj/argo-cd/issues/11261 for why rancher-monitoring is `ok` for `Progressing` status
          expr: |
            (argocd_app_info{health_status!="Healthy",name!="rancher-monitoring"} == 1
            or argocd_app_info{health_status!~"Healthy|Progressing",name="rancher-monitoring"} == 1)
          for: 2h
          labels:
            severity: critical
          annotations:
            summary: "[{{`{{$labels.name}}`}}] Application not healthy"
            description: >
              The application [{{`{{$labels.name}}`}} has not been healthy for over
              2 hours.
        - alert: ArgoAppAutosyncDisabled
          expr: |
            argocd_app_info{autosync_enabled="false"} == 1
          for: 2h
          labels:
            severity: info
          annotations:
            summary: "[{{`{{$labels.name}}`}}] Application autosync not enabled"
            description: >
              The applications [{{`{{$labels.name}}`}} autosync has been deactivated for over
              2 hours.
  dex:
    enabled: true

  server:
    ingress:
      enabled: true
      hostname: argocd.blindfolded.surgery
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        cert-manager.io/issue-temporary-certificate: "false"
        kubernetes.io/tls-acme: "true"
      tls: true
      ingressClassName: nginx
      https: false

  applicationSet:
    enabled: false

  notifications:
    enabled: false
